title: "Jin Ho Yun"
description: "Jin Ho Yun is an Assistant Professor of Marketing at New Mexico State University studying consumer behavior, advertising, AI, and neuroscience."
url: "https://drjyun.github.io"
baseurl: ""
email: "drjyun@nmsu.edu"
repository: "drjyun/drjyun.github.io"
google_analytics: "G-V1QVKG4ENS"
markdown: kramdown
permalink: pretty

exclude:
  - .DS_Store
  - .Rhistory
  - README.md
